apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
spec:
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest
  ports:
    - name: jaeger-collector-http
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: jaeger-collector-grpc
      protocol: TCP
      port: 14250
      targetPort: 14250
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
spec:
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/name: simplest
  ports:
    - name: jaeger-ui
      protocol: TCP
      port: 16686
      targetPort: 16686
  type: LoadBalancer
